### ISSUE TITLE
Can't resize windows (settings not visible)

### ISSUE THREAD

**Issue by digitalnomad91** [SamsidParty/TopNotify#10]
![image](https://github.com/SamsidParty/TopNotify/assets/2067771/3c01d069-2db6-445f-9966-c2b12ac8da3c)

![image](https://github.com/SamsidParty/TopNotify/assets/2067771/0bfe517c-ce11-4779-95cf-b51f187134b9)

I can't resize the windows and therefore can't see the settings or confirm my custom positioning :/

**Comment by digitalnomad91** [comment]
Okay so I installed via microsoft store instead and I still can't resize but now I can at least scroll down. Also the custom window shows the full text now (it's just pretty tiny).

**Comment by SamsidParty** [comment]
Try holding the control key and scrolling up/down to zoom in and out.
