### ISSUE TITLE
Custom position reset on display change

### ISSUE THREAD

**Issue by bel57** [SamsidParty/TopNotify#11]
Hello,
I'm frequently switching between full screen and split screen. I've noticed that TopNotify doesn't always check screen resolution.
After switching back from split (right) to full, custom position is not following saved coordinates. It gets stuck in the middle of the screen instead. Relaunching and setting back the custom position fixes it.
I think the app should monitor display changes (resolution, position) or force apply custom position instead of reverting to middle. Maybe your app is relying on Windows to get the borders of the screen and it's a bug with the OS, idk.

Windows 11 and latest version of TopNotify
Screenshot to better explain the issue:
![topnotify-custom-issue](https://github.com/SamsidParty/TopNotify/assets/10614811/c630a2f1-e072-4c1e-a4fd-0d1155ff2fb7)

After that I've deleted portable exe and installed UWP version instead (just found out it was available on Windows Store!).
Will report if it's occuring again. Thanks!

**Comment by SamarthMP** [comment]
So is it fixed in the MS Store version?
The MS store version uses a different API to detect screen resolution (The certification team was very particular about screen scaling)
I will push an update to the portable version soon to have feature parity with the store version.

**Comment by bel57** [comment]
It's the weekend for me so I'm back to full screen. Will get back to you in the following week when experimenting display scenarios again, if any issue arises.
According to your comment I think that's the fix I needed. Thanks!
