### ISSUE TITLE
Issue with high resolution monitor

### ISSUE THREAD

**Issue by realgooseman** [SamsidParty/TopNotify#14]
Hi @SamsidParty,

Thanks for this very useful utility.
I found an issue on my 4k monitor (3840x2160 @ 200% scale) (probably for other high resolutions as well).
The TopNotify window shows up in a weird disposition where the buttons overlap, might be related to high-DPI problem ?

Also, the test notifications show up cut in half on screen when using the preset placements (top left, top right, bottom left, bottom right) and I have to use the custom option to place the notification flyout correctly.

**Here is a picture of the issue:**
![TopNotify 4K](https://github.com/SamsidParty/TopNotify/assets/64812183/a2c0022f-eafc-4f87-9f05-e32b97f77cce)

**Comment by SamsidParty** [comment]
Hello, are you using the Microsoft store version of the app or the older exe version? The store version contains scaling fixes, please use that one.

**Comment by realgooseman** [comment]
I was using the EXE version because I was getting an error when trying to install it from the Microsoft Store. Can"t install it from the store.

**Comment by SamsidParty** [comment]
Can you try downloading version 2.3.7 as an msix file and running that to install it? I'm not sure how to fix that error with the store.

**Comment by realgooseman** [comment]
Just installed the MSIX file, same problem. Buttons on the window get overlaped and the window is small.

**Comment by SamsidParty** [comment]
For the UI, can you try using Ctrl + scroll wheel up/down? Also, do the preset placements still cut off? I don't have a 4K monitor to test this and I couldn't get the VM to run in 4K.

**Comment by realgooseman** [comment]
I've had a few DPI/scaling issues with software since I got my 4k monitor. Seems like TopNotify has the same issue.
![TopNotify 4K](https://github.com/SamsidParty/TopNotify/assets/64812183/e16b47c1-f0b6-4345-87ba-c3bd49c306f3)

**Comment by SamsidParty** [comment]
I'll see what I can do.

**Comment by SamsidParty** [comment]
I'll see what I can do.

**Comment by SamsidParty** [comment]
Can you try the beta 2.4.0? That might have fixed it. If not, more betas will come soon that address this issue better.

**Comment by SamsidParty** [comment]
fixed in version 2.4.1
