### ISSUE TITLE
Blank window and out of border notifications on screen change

### ISSUE THREAD

**Issue by bel57** [SamsidParty/TopNotify#15]
Hello,

Not a Custom position reset on display change #11 dupe.
There's an issue with TopNotify where when you're switching between monitors/display configuration, the app window goes blank (had to restart the app for it to display properly) and the notifications don't appear within screen frame (out of border).
I can hear the sound but they don't appear. For what it's worth, using custom position.
After switching to one of the set positions (corner) it's working.

I think the app should remember the relative position instead of saving screen coordinates.
I'm not sure if it's a TopNotify issue or a Windows API issue cause it can happen with other apps too. Not sure why Microsoft wouldn't implement a safe area where forcing apps to not draw out of border.
Can you look into this? Thanks

Btw I noticed this only recently cause usually I only use PBP (half) or full (4K) screen. This behavior happens when I switch from 4K monitor to FHD (laptop screen).
![image](https://github.com/SamsidParty/TopNotify/assets/10614811/7b2fe39b-2726-49cd-9fdd-46a39e6cec3d)

**Comment by SamsidParty** [comment]
I believe these 2 bugs are separate. For the blank window bug, does pressing F5 do anything? If so then that bug is already fixed in the beta and will release before the end of July. As for the other bug, I still have to do some investigation.

**Comment by bel57** [comment]
That's possible, I will give it a shot if it occurs again. Sorry for filing the 2 issues into 1 report.
Thanks for the fast reply as always.

**Comment by SamsidParty** [comment]
Unfortunately I won't be able to work on these issues for a while since I'm on vacation. I'll look into it after I come back.

**Comment by bel57** [comment]
Okay no rush, please enjoy your vacay 😎

**Comment by SamsidParty** [comment]
I have managed to troubleshoot this issue, and completely reworked the way custom positions are stored.
They are now stored as a percentage value instead of a pixel value, so it will work with scaling properly.
Look out for version 2.4.1, hopefully coming soon.

**Comment by bel57** [comment]
Excellent, thank you. Will reach out if there's any problem occuring with the new version.

**Comment by SamsidParty** [comment]
Version 2.4.1 is live on the microsoft store, note that you will have to redo the custom position setup because the method of storing it  has changed.

**Comment by bel57** [comment]
Seems to be working on my PC but ok my workstation it doesn't, despite custom bottom right position it's spawning in the top left. Also for some reason the settings window is see-through, no background.

**Comment by SamsidParty** [comment]
is your workstation running windows 10 or 11?

**Comment by bel57** [comment]
Sorry for the missing details. My PC is on Win11 latest build and my workstation is running Windows 10 22H2 build 19045.4412

**Comment by SamsidParty** [comment]
Windows 10 explains the blank window part, can you try just restarting TopNotify? I think there might be a bug with the config files.

**Comment by bel57** [comment]
Already restarted the app. But your comment pointed le in the right direction.
It's working fine after wiping app data (reset via windows settings).

**Comment by SamsidParty** [comment]
Glad it finally works, can I close this issue now?
