### ISSUE TITLE
App doesn't start when startup is set to enabled

### ISSUE THREAD

**Issue by Asteski** [SamsidParty/TopNotify#17]
After I've installed latest version, TopNotify doesn't start automatically when I've set startup mode to enabled. Setting this up in both task manager and using powershell doesn't work. I really want to avoid putting shortcut in startup folder or use task scheduler ot run it, as I want TN to be deployable automatically, and be able to run itself after restart.

**Comment by SamsidParty** [comment]
can you send a screenshot of the GUI?

**Comment by Asteski** [comment]
![Screenshot 2024-07-17 120505](https://github.com/user-attachments/assets/4325c611-72d6-461b-8048-3d6a926a2e81)
