### ISSUE TITLE
Not supporting RTL languages

### ISSUE THREAD

**Issue by aravon72** [SamsidParty/TopNotify#18]
I'm using Windows 11 in Hebrew which means the GUI is Right to Left. When in this state, the notification will keep showing in Windows' default place (low left corner), no matter what.
Will you please be able to support RTL GUI as well?

TIA.

**Comment by SamsidParty** [comment]
Hi, I don't think this is an issue with right-to-left languages, I think it's an issue with the fallback interceptor.
Can you try setting your system display scale to 100%?

**Comment by aravon72** [comment]
> Hi, I don't think this is an issue with right-to-left languages, I think it's an issue with the fallback interceptor. Can you try setting your system display scale to 100%?

Currently I'm in English GUI scaled to 100% and it works properly.
Staying in English GUI but changing scale to 125% - indeed seems to be problematic. Sound works but only shows notification when set to upper right corner or custom.
But if I quit TopNotify (from the task bar icons) and run it again - all works.

Now moving back to Hebrew GUI and 100% scale - As said in my original post - all shows in the left bottom corner.
Same goes when scaling to 125%, after closing TopNotify and reopening.
By the way, TopNotify's UI is too big. In 125% scale it almost uses the whole height of the screen.

Adding screenshot while in Hebrew GUI.
![image](https://github.com/user-attachments/assets/ab0d8d22-d019-4b15-8c01-0111c7982ec8)

**Comment by SamsidParty** [comment]
Interesting, I'll try to replicate the Hebrew issues in a virtual machine. As for the scaling messing up until restart, that will be fixed in the next release.

**Comment by aravon72** [comment]
Also try to reduce the size of the panel. There's about a third of free space.

**Comment by SamsidParty** [comment]
Hebrew support has been added, Issue will be fixed in the next release.

**Comment by aravon72** [comment]
Wow. Great. Thank you for being so responsive.
I've also created a YouTube video for my channel yesterday about TopNotify. I'll be happy to update my audience once there's a new version.
