### ISSUE TITLE
Position issue

### ISSUE THREAD

**Issue by davresmor** [SamsidParty/TopNotify#19]
The notification position is messed up, and fixes? Just downloaded this app now. 
![Screenshot 2024-08-20 120615](https://github.com/user-attachments/assets/42768e75-6eb2-4876-acfb-df67a0e79660)
Any fixes?

**Comment by SamsidParty** [comment]
Did you happen to change displays or display scaling recently? Try restarting the app. Fixes for scaling are coming in the next update.

**Comment by davresmor** [comment]
Didn't change any scaling or display, restarted my PC 4 times. ETA of update? Thanks

**Comment by bel57** [comment]
Thanks for creating this issue, I was about to. Can't wait for the update, notifications still appear out of borders. Not even half of the banner is displayed on screen:
![image](https://github.com/user-attachments/assets/03ae0380-6039-49ed-b4cc-23af1380a82b)

**Comment by SamsidParty** [comment]
I'll push the update out ASAP, if the issue still persists then let me know.

**Comment by SamsidParty** [comment]
Update is out

**Comment by davresmor** [comment]
I uninstalled and reinstalled, no change for me

**Comment by SamsidParty** [comment]
Interesting, I'll have to look into it, can you send me the specs of your monitor?
Does the custom position work?

**Comment by davresmor** [comment]
I'm running a surface pro 9 without an external monitor right now. here's another screenshot
![Screenshot 2024-08-21 114404](https://github.com/user-attachments/assets/d9cd4d6e-e4c3-4e40-8468-21987cbd0887)

Custom position doesn't work either, and whenever I try switching between the other angles it doesn't work.

I took a video recording but its too big for Github do you have any other place I can send it?

**Comment by SamsidParty** [comment]
send it to business@samsidparty.com via email

**Comment by davresmor** [comment]
will try rn

**Comment by SamsidParty** [comment]
Another thing, do you have the ARM/5G version of the surface pro? TopNotify currently doesn't support ARM properly and may act weird.

**Comment by davresmor** [comment]
Nope I don't have the arm version

**Comment by bel57** [comment]
Not fixed. Running v2.4.2.0, switching between 4K (full screen) and half split screen Picture by Picture mode (1920x2160) the notification is still clipping out of bound. It even appears like that in the GUI..
Please fix code/coordinates so the app remember a relative position and forces padding so the banner is always fully shown on screen.
![temp](https://github.com/user-attachments/assets/84d1cb28-8270-4d84-81df-3679e2e20b1e)

**Comment by SamsidParty** [comment]
I see, well vertical monitors were never accounted for in the code, I can try to force a padding on the notification.

**Comment by SamsidParty** [comment]
@bel57 Just added some out-of-bounds correction code, will be in the MS store soon.
I know you've been following TopNotify since the beginning, so I would appreciate it if you could [nominate](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR_lzdMcHC_tMqWeRwoTd7TRUMlZZWk5ZUk1JU0Q4RU03S1BKU0xHRExNVi4u) it for the ms store awards.

**Comment by bel57** [comment]
Perfect! Sure, just filed the form. Good luck! It deserves some recognition as it's a never seen but essential feature that MS should have added years ago.

**Comment by SamsidParty** [comment]
Great! And update 2.4.3 which fixes this issue is live on the MS store.

**Comment by bel57** [comment]
Updated, checked GUI, didn't have to reposition. There's padding!
Thanks for the fix 👍
