### ISSUE TITLE
TopNotify works but does not open

### ISSUE THREAD

**Issue by MichaelPro999** [SamsidParty/TopNotify#20]
hello

i am using TopNotify latest version and it is does work but when i try to open the TopNotify window it is shows the TopNotify window trying to open for a second and then close and i i can't access the settings.
![image](https://github.com/user-attachments/assets/199f0925-4a0e-4ab6-b605-950e90cd8fd1)

**Comment by SamsidParty** [comment]
What version of windows are you using? 
Make sure you have the webview2 runtime installed

**Comment by MichaelPro999** [comment]
hello, im using the latest version of windows 10, also i installed the Microsoft Edge WebView2 and now it is working, thanks
