### ISSUE TITLE
Rounded/Radius settings for Notifications

### ISSUE THREAD

**Issue by Crunchbits** [SamsidParty/TopNotify#22]
Perhaps outside the scope for this project but if feasible it'd be great to have the ability to change the notification corners to be rounded(Windows 10's straight corners would look visually better).

**Comment by SamsidParty** [comment]
It would be great to be able to modify the UI of the notifications, but it's currently very difficult to modify XAML UI. Unfortunately, the notification process (ShellExperienceHost.exe) cannot be injected, I have tried almost every way possible. Maybe in the future I will find a way to make it work, but for now it's not feasible.
