### ISSUE TITLE
TopNotify consuming ~5-9% cpu

### ISSUE THREAD

**Issue by science** [SamsidParty/TopNotify#23]
TopNotify is working correctly but it is consuming what seems like an excessive amount of CPU. This is maybe new - I haven't noticed this in the past, but maybe it has always been going on (since I installed a few months ago).

CPU utilization (that seems pretty typical):
![image](https://github.com/user-attachments/assets/56e2d454-3207-4127-bdbf-da471206920f)

Let me know if you need additional debug data. I LOVE your application - it's appalling that Windows doesn't permit configuration natively for this, so thank you so much for creating this!

System info:
![image](https://github.com/user-attachments/assets/95c91ab3-25a6-45eb-b211-f1c0c0dbdfeb)

**Comment by SamsidParty** [comment]
New performance improvements are coming in version 2.4.4. In the mean time, you can try out the [beta](https://github.com/SamsidParty/TopNotify/releases/tag/2.4.4-beta2), which has some of these improvements already (Make sure you uninstall the store version first). Also, if the TopNotify settings panel is closed, it should use way less CPU.

**Comment by SamsidParty** [comment]
Version 2.4.4 is now available, it fixes most performance issues. Please update TopNotify.

**Comment by science** [comment]
@SamsidParty - thank you. I didn't get notified by GH about your reply, so apologies for the slow response. The app now consumes 0.1-0.5% of CPU which seems much more reasonable. You can consider this confirmation of your fix! I've been so distressed by the bottom right notifications since I stopped using TopNotify. I'm glad to have it back!
