### ISSUE TITLE
Notifications showing on main monitor instead of second

### ISSUE THREAD

**Issue by goffmann-op** [SamsidParty/TopNotify#24]
Had assigned notifications on my second monitor (which is Portrait oriented and is not main), now all notifications is showing on first main monitor.
I can still move it in [Custom position] state on second monitor, but when I press [Spawn test notification] they are spawning on main one.

Seems like last update broke it.

**Comment by SamsidParty** [comment]
Yes, I did indeed make changes that would display the notification only on the main monitor. This is for proper scaling to work. I am planning to add multiple monitor support in a future release. I will try to make a beta version with temporary multi-monitor support until I can implement it properly.

**Comment by goffmann-op** [comment]
That would be great. 
Thank you in advance.

**Comment by SamsidParty** [comment]
Version 2.4.5 has been released with a workaround:

- Press F2 On The TopNotify GUI
- Turn On The Switch "Disable Bounds Correction"
- Now Set The Custom Position To Your Other Monitor

Now you will be able to see notifications on your other monitor.

**Comment by Skyyblaze** [comment]
This is amazing thank you! One question, would it in the future be possible to save the notification position per monitor-layout? I don't always have my second monitor enabled so when it isn't enabled I would like notifications to be on the top right of my primary monitor and when it is enabled I would want them on the top left of my second monitor.

**Comment by SamsidParty** [comment]
This is planned for a future release.

**Comment by Skyyblaze** [comment]
> This might be implemented in the future, more specifically, I might add a scripting system so you can write code to position the notifications depending on your hardware config.

I see, well then I hope this eventually pans out but if not no worries!
