### ISSUE TITLE
unable to click on the minimize, restore, close windows buttons when the topnotify is in the upper right mode

### ISSUE THREAD

**Issue by MichaelPro999** [SamsidParty/TopNotify#25]

**Comment by khaleel2788** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by SamsidParty** [comment]
If you enable click-through mode, you should be able to.

**Comment by MichaelPro999** [comment]
what is the click-through mode

**Comment by SamsidParty** [comment]
If you open TopNotify, you'll see a switch that enables click-through mode. When it's on, you can click the stuff behind notifications, including the minimize/maximize/close buttons on maximized windows.

**Comment by MichaelPro999** [comment]
okay it is working thanks, i wish i knew about this sooner

**Comment by MichaelPro999** [comment]
but the problem is that now i can't click on the notifications and get to the massages in discord for example

**Comment by SamsidParty** [comment]
If you turn off click-through, it shouldn't affect the ability to click on the window buttons. Please upload a video of your problem.
