### ISSUE TITLE
The application UI is transparent

### ISSUE THREAD

**Issue by thowoee** [SamsidParty/TopNotify#26]
When opening the application the view is fully transparent.

Windows: Windows 10 Pro (22H2, 19045.4842)
Microsoft Edge WebView2 Runtime: 128.0.2739.54

Application installed from the Microsoft store.

![image](https://github.com/user-attachments/assets/44388fe8-287a-4538-97df-718cfe9eca0a)

**Comment by SamsidParty** [comment]
Interesting, I will see what I can do.

**Comment by SamsidParty** [comment]
Version 2.5.5 is released, please check if it's fixed.
