### ISSUE TITLE
Custom notification position

### ISSUE THREAD

**Issue by bel57** [SamsidParty/TopNotify#3]
Hello,

Now that the app is working on my system, a UI fix/suggestion.
For users who have the taskbar on the top of the screen instead of the bottom, please add a padding to avoid an overlap.
Also would be great to have custom padding/position in the options.
Thanks

![image](https://github.com/SamsidParty/TopNotify/assets/10614811/cd93cb48-f3f5-44fe-abb6-96fa6925a495)
![image](https://github.com/SamsidParty/TopNotify/assets/10614811/608e0a93-8c73-418a-b583-bbd3c762aaa2)

Win11 23H2
v2.1.3
fr-FR

**Comment by SamarthMP** [comment]
I am planning to add a custom notification position feature, I'll see what I can do.

**Comment by SamsidParty** [comment]
Custom positions are now available, please update to version 2.3.0
