### ISSUE TITLE
Notifications in top right corner of center monitor are split 50/50 with right monitor (low priority due to work-around)

### ISSUE THREAD

**Issue by science** [SamsidParty/TopNotify#30]
*Hardware Context:*
 Win 10 latest, with a three monitor setup (Left, Center (primary), Right)

*Problem description:*
I have TopNotify setup to put notifications in the top right corner. When the notifications are presented, they are split seemingly 50/50 with left half of the card appearing on the top right corner of center/primary monitor, and right half of the card appearing on the top left corner of the right hand monitor.

Here is a screenshot which depicts the notification split across these two monitors (the browser window in the background of the image is maximized on the center monitor):
![image](https://github.com/user-attachments/assets/2f27e47d-ab6e-4bab-9d18-884ef1afe401)

*Priority:*
I think this is a low priority bug because I can fix it by using custom notification positioning. But I thought you'd like to know about it.

*Steps to reproduce:*
Set up a three monitor system, and ensure the center monitor is primary. Configure TopNotify to notify on upper right. Send a test notification in TopNotify. Notice placement problem.

*Additional issues note:*
1) Bottom right notification seems broken but in a different way: the notification is both clipped at the bottom, and split across center and left monitors.
![image](https://github.com/user-attachments/assets/d4a6898d-201e-4b01-923c-d2ea03409918)
2) Bottom left notification seems broken but in a different way: the notification is clipped at the bottom, but appears fully in the center monitor (not spread across left and center monitors):
![image](https://github.com/user-attachments/assets/63da0c2d-d6f2-4edd-bdbc-35f23f7797d3)
3) But notably upper left notification is working fine.
4) Custom positioning also works fine, so I placed the notification in the upper right corner of the main monitor manually, and things are fine for me now.

Let me know if you'd like additional information!

**Comment by SamsidParty** [comment]
Do your monitors have different scaling values?

**Comment by science** [comment]
Yes - right now set to 175% 
![image](https://github.com/user-attachments/assets/1f7a859c-ae8b-40ac-9a03-b970a96db358)

And apologies for missing this issue which looks like the single monitor version of the same problem: https://github.com/SamsidParty/TopNotify/issues/29

**Comment by science** [comment]
But specifically noting that my monitors all have the same scaling value (and are all 1080p external monitors).

**Comment by SamsidParty** [comment]
TopNotify currently gets the scaling value from the primary monitor, are your monitors all the same resolution, and are any of them portrait mode?

**Comment by SamsidParty** [comment]
Looks like the last update broke this, will be fixed in 2.4.6
