### ISSUE TITLE
Display notifications on another monitor

### ISSUE THREAD

**Issue by zoetrope69** [SamsidParty/TopNotify#33]
Do you think there would be a way on multiple monitors to pick which monitor the notification appears on?

Thanks for this software it's great.

**Comment by SamsidParty** [comment]
This feature is coming in the future, but it's possible right now using the custom position. Just press F2 and disable bounds correction. Then, you can position notifications on another monitor.

**Comment by terax6669** [comment]
Needs some kind of fix when the second monitor uses scaling (I'm at 125%).

![image](https://github.com/user-attachments/assets/fce0b17c-ed0a-4e7c-8f6c-e586b17938bb)

**Comment by SamsidParty** [comment]
I'll keep that in mind for the next batch of scaling changes.

**Comment by SamsidParty** [comment]
This has been implemented into the source code and will make it to the Microsoft store by December hopefully.
As for that scaling problem, it's windows's fault, it will set the notification size based on the primary monitor, but its contents will grow too big if it's on the secondary monitor with a larger scale, which causes the clipping. I will try to find a workaround.

**Comment by SamsidParty** [comment]
Added in 2.6.0

**Comment by zoetrope69** [comment]
Thank you!
