### ISSUE TITLE
Crash after update

### ISSUE THREAD

**Issue by Lazysmurf74** [SamsidParty/TopNotify#36]
Nome dell'applicazione che ha generato l'errore: TopNotify.exe, versione: 1.0.0.0, timestamp: 0x66960000
Nome del modulo che ha generato l'errore: KERNELBASE.dll, versione: 10.0.22621.4391, timestamp: 0x7433a115
Codice eccezione: 0xe0434352
Offset errore 0x000000000005fa4c
ID processo che ha generato l'errore: 0x0x44AC
Ora di avvio dell'applicazione che ha generato l'errore: 0x0x1DB3D8CCCD09A54
Percorso dell'applicazione che ha generato l'errore: C:\Program Files\WindowsApps\55968SamsidGameStudios.TopNotify_2.6.0.0_x64__r9j5xrxak4zje\TopNotify.exe
Percorso del modulo che ha generato l'errore: C:\WINDOWS\System32\KERNELBASE.dll
ID segnalazione: d18a44aa-9d35-4df3-bbe7-83361c3ad925
Nome completo pacchetto che ha generato l'errore: 55968SamsidGameStudios.TopNotify_2.6.0.0_x64__r9j5xrxak4zje
ID applicazione relativo al pacchetto che ha generato l'errore: TopNotify

Application: TopNotify.exe
CoreCLR Version: 8.0.824.36612
.NET Version: 8.0.8
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Security.Principal.IdentityNotMappedException: Some or all identity references could not be translated.
   at System.Security.Principal.NTAccount.Translate(IdentityReferenceCollection sourceAccounts, Type targetType, Boolean forceSuccess)
   at System.Security.Principal.NTAccount.Translate(Type targetType)
   at System.Security.AccessControl.CommonObjectSecurity.ModifyAccess(AccessControlModification modification, AccessRule rule, Boolean& modified)
   at System.Security.AccessControl.CommonObjectSecurity.AddAccessRule(AccessRule rule)
   at TopNotify.Daemon.SoundInterceptor.EnsureFakeSoundValidity()
   at TopNotify.Daemon.SoundInterceptor.Start()
   at TopNotify.Daemon.InterceptorManager.Start()

**Comment by SamsidParty** [comment]
Hello, it seems the "ALL APPLICATION PACKAGES" group is missing on your computer.

You can add it by running the following command as an administrator:
`net localgroup "All Applications Packages" /add`

**Comment by Lazysmurf74** [comment]
Ops. So problem is mine. Will try as soon as possible.Sorry for the bother and thanks for the reply and the help 😊Il 23 nov 2024 11:03, SamsidParty ***@***.***> ha scritto:
Hello, it seems the "ALL APPLICATION PACKAGES" group is missing on your computer.
You can add it by running the following command as an administrator:
net localgroup "All Applications Packages" /add

**Comment by SamsidParty** [comment]
It may not be your fault, but this is the first troubleshooting step I can think of.

**Comment by Lazysmurf74** [comment]
Okie. Tried but got message that "the local group already exists"
Tried to run app as admin, same.
Before the last updated it never ha

Il giorno sab 23 nov 2024 alle ore 11:44 SamsidParty <
***@***.***> ha scritto:

**Comment by SamsidParty** [comment]
While we investigate, you can install the previous version of TopNotify [here](https://github.com/SamsidParty/TopNotify/releases/download/2.4.5/TopNotify.Msix) which doesn't have the crashing issues.

**Comment by Lazysmurf74** [comment]
Okie 😊
Thanks for the link. And good job with the app..simple but very useful

Il giorno dom 24 nov 2024 alle ore 18:55 SamsidParty <
***@***.***> ha scritto:

**Comment by bel57** [comment]
Hello, I received the app update through Windows Store today and turns out I got the exact same issue.
Win11 24H2. Will wait for a fix, I saw you provided previous version installer in another thread.
Thanks.

**Comment by bel57** [comment]
@SamsidParty hello, any news? The software still becomes unresponsive and crashes on launch, even the new version.
I got the same logs as OP, it's quite inconvenient to prevent Windows Store updating it/force downgrade every time.
Thank you for looking into it.

**Comment by SamsidParty** [comment]
Still trying to find a fix, I know what's going wrong but don't know how to fix it.

**Comment by Skyyblaze** [comment]
I also have been experiencing crashes after the latest updates from the store, the last version on Github still works fine. Any newer version of TopNotify opens and works for about 3 seconds until it closes itself with no error message.

I'm using Windows 11 Pro 24H2 26100.2314.

**Comment by MagicAndre1981** [comment]
I also get a crash under Windows 10 22H2 19045.5131:

> In TopNotify.exe.3016.dmp the assembly instruction at KERNELBASE!RaiseException in C:\Windows\System32\KERNELBASE.dll from Microsoft Corporation has caused a CLR Exception on thread 12 with the following error information:
> 
>     Type:   System.Security.Principal.IdentityNotMappedException 
>     Message:   Some or all identity references could not be translated. 
> 
> This exception originated from System_Security_Principal_Windows!System.Security.Principal.NTAccount.Translate(System.Security.Principal.IdentityReferenceCollection, System.Type, Boolean).

![image](https://github.com/user-attachments/assets/fc650fb3-f2eb-43e3-9249-07bd68458468)

**Comment by SamsidParty** [comment]
Yeah I'm sorry but my portable PC broke and I only have access to a mac (can't bootcamp/run vm) and since I'm traveling I won't be able to help until Christmas time.

**Comment by bel57** [comment]
Okay no worries, thanks for the honest reply.
Can you maybe pull the latest update from Windows Store so it doesn't try to update the app again and again?
Happy Holidays

**Comment by SamsidParty** [comment]
Ok, I'll see what I can do since half the people have crashes and the other half like the multi monitor support.

**Comment by SamsidParty** [comment]
I managed to get access to a windows machine, I'll try to fix it.

**Comment by Skyyblaze** [comment]
Thank you for your hard work!

**Comment by SamarthMP** [comment]
Looks like the "ALL APPLICATION PACKAGES" group is missing on certain machines, are you guys using windows home or pro?

**Comment by SamarthMP** [comment]
I've fixed this issue by simply try/catching the code that sets the permissions. The code block isn't really necessary for the current versions of windows but is for future proofing in case Microsoft changes something.

**Comment by SamsidParty** [comment]
I'll be releasing a beta version soon with the issue fixed.

**Comment by MagicAndre1981** [comment]
> Looks like the "ALL APPLICATION PACKAGES" group is missing on certain machines, are you guys using windows home or pro?

I use German Windows 10 Pro 22H2 19045.x, here user/group names are different. VMware also had such an group issue with 17.6 installer.

**Comment by SamsidParty** [comment]
I see, well it seems setting this permission is not necessary because if it's unset windows will play no sound, which is what we want. So please install the beta until 2.6.1 is released to the store.

**Comment by MagicAndre1981** [comment]
FYI on my German Windows the group is called "ALLE ANWENDUNGSPAKETE" 

![image](https://github.com/user-attachments/assets/e825759d-89ef-4e43-bd9d-8d1bfce3c61b)

So never check for English names, this will fail on other langauges.

**Comment by SamsidParty** [comment]
Yup, this always happens with windows and has been troubling since the creation of TopNotify. If only Microsoft had a way to access the localisation values of the system.

**Comment by MagicAndre1981** [comment]
>  If only Microsoft had a way to access the localisation values of the system.

the [WellKnownSidType enum](https://learn.microsoft.com/en-us/dotnet/api/system.security.principal.wellknownsidtype?view=net-8.0) should work for normal desktop apps, but I have no idea if this also works for store packed applications. 

Here `WinBuiltinAnyPackageSid` should be the correct entry.
