### ISSUE TITLE
New notification sounds

### ISSUE THREAD

**Issue by robbely** [SamsidParty/TopNotify#38]
After the update 2.6.0.0, the app ignores my (custom) windows notification sounds setting and uses something else. How can I change this back?

**Comment by SamsidParty** [comment]
TopNotify is designed to take control of the windows notification sounds, if you want to change them, you can use the "Edit Notification Sound" button in TopNotify.

**Comment by robbely** [comment]
The previous version didn't have this issue, so something has changed. Do I need to edit every app after it makes it's first notification or is there a way to make the sound I want the default? And how do I use the one windows uses without having to copy sounds into my music folder?

**Comment by SamsidParty** [comment]
Yes, the custom notification sound feature was added in 2.6.0, there is an option for the default notification sound at the top called "All Other Apps" that will be used as the default sound unless you override a specific app. When you choose a sound, at the bottom there will be a section where you can choose the windows 10 or 11 sound.

**Comment by robbely** [comment]
Many thanks. The "All other apps" sounds useful but I can't find it, the notification sound panel only lists the apps that so far have given a notification.

Also, as the previous version worked perfectly for me, is there a way to revert without Windows updating it again?

**Comment by SamsidParty** [comment]
Can you please send a screenshot of the "Notification Sounds" panel?

**Comment by robbely** [comment]
![notifpanel](https://github.com/user-attachments/assets/3c11d357-d7bc-435f-8f35-c0485e547873)

**Comment by SamsidParty** [comment]
> I had tried that, windows store just updated it again to the latest version.

I see, I don't know why microsoft does that, the closed off MSIX platform is not very well documented.

**Comment by robbely** [comment]
> I see, I don't know why microsoft does that, the closed off MSIX platform is not very well documented.

I did try moving the installation folder so that microsoft wouldn't touch it, but I guess it has to be installed as a package as the app gave errors (not being able to capture notifications)

**Comment by SamsidParty** [comment]
Yup, that's why it's an MSIX in the first place, can't capture notifications as a win32 app.
However, installing the beta versions of TopNotify or compiling from source won't update from the store, but they use self signed certificates and won't be validated and signed by Microsoft,

**Comment by robbely** [comment]
Unless it was a beta of the older version that wouldn't help lol. Anyway I think it's sorted now (and I know where to look if a later update breaks it again). Many thanks for your time on this :) I'll close it as completed now
