### ISSUE TITLE
Add polish language support

### ISSUE THREAD

**Issue by Sauler** [SamsidParty/TopNotify#4]
Hi,

Please add polish language support in Notification Interceptor  ❤️ 
Language code: PL
Text: Nowe powiadomienie

**Comment by SamarthMP** [comment]
Sure! Give me 30 mins

**Comment by SamarthMP** [comment]
Polski has been added, please update to 2.1.5

**Comment by Sauler** [comment]
Working perfectly now. Thank you ❤️
