### ISSUE TITLE
Part of the shadow has been cut off

### ISSUE THREAD

**Issue by Pein1911** [SamsidParty/TopNotify#41]
Anyone has this bug ?

Win 11 24H2 26100.2454
![Screenshot 2024-11-29 143019](https://github.com/user-attachments/assets/223271d6-452a-4260-ac03-354c81d96fe2)

**Comment by SamsidParty** [comment]
Hello, this is because the shadow is part of the notification window, and cannot be controlled by TopNotify. You can fix it by increasing the transparency of the notification.
