### ISSUE TITLE
After running a newer version of TopNotify my Notifications are now always silent despite reverting to a previous version

### ISSUE THREAD

**Issue by Skyyblaze** [SamsidParty/TopNotify#44]
After I got crashes with the latest TopNotify version from the Microsoft Store I uninstalled it and installed the latest version from Github. Now TopNotify works again but I lost all notification sounds unless the app itself provides a sound. I also already went into the Windows Sound Settings and reassigned my Notification Sound but my notifications remain silent.

How can I restore my notification sounds?

I'm running Windows 11 24H2 26100.2314

**Comment by SamsidParty** [comment]
When setting the notification sound to the default, what did you set it to?

**Comment by Skyyblaze** [comment]
@SamsidParty I set it to a .wav file I was using before in the Classic Sound Panel of Windows. I never got to set any sound in TopNotify as the version of TopNotify that enables sound customization won't work on my system.

**Comment by SamsidParty** [comment]
Try setting it to the default sound in "C:\Windows\Media" because the file needs to have a special permission set in order for windows to play it.

**Comment by Skyyblaze** [comment]
> Try setting it to the default sound in "C:\Windows\Media" because the file needs to have a special permission set in order for windows to play it.


Oh that was it, thank you! I forgot the sounds had to be there to work. I had them in my "Customization" folder but I also copied them to Media and forgot about that when TopNotify blanked it. So it isn't a TopNotify bug after all, I'm sorry.
