### ISSUE TITLE
Custom notification opacity

### ISSUE THREAD

**Issue by Sauler** [SamsidParty/TopNotify#5]
Hi,

It would be perfect if it was possible to set a custom opacity instead of predefined one.

**Comment by SamarthMP** [comment]
I was planning to, but the component library I was using (NextUI 1.0) doesn't have a slider component.
I'll see if I can add another way to change the opacity with more finely adjustable controls.

**Comment by SamarthMP** [comment]
Alright, in version 2.1.6, you can edit the settings file directly and add decimal values to the "Opacity" field.
"Opacity" should be between 0 (Fully Opaque) to 5 (Fully Transparent).
You can find the settings file at %LOCALAPPDATA%/SamsidParty/TopNotify/Settings.json

A more user-friendly method of changing it is not currently planned.
